### ISSUE TITLE
Display Recyclability

### ISSUE THREAD

**Issue by sahanabela** [acm-projects/To-Toss-or-Not-to-Toss#12]
Front end:
- [x] Display image on results screen once you upload it- Tisha
- [x] Recieve information from back-end about its "recyclability"- Abdul
- [x] Show the user whether the item can be recycled- Tisha

Backend:
- [x] Send "recyclability" information to front end

**Comment by arxfxi** [comment]
First had to set up the tflite model to work on dart then connect it to local data. Then connected results to recycleable pages
