### ISSUE TITLE
Make ML model

### ISSUE THREAD

**Issue by sahanabela** [acm-projects/To-Toss-or-Not-to-Toss#7]
Recognize the image uploaded and determine if it is recyclable or not.

**Comment by Sohailm25** [comment]
I managed to build a model on top of a pre existing MobileNet CNN model. I used a dataset from kaggle, imported their API, and built the model.

I'm currently working on improving the dataset and seeing if other options have better accuracy, including augmentations/dropouts.

You can export the model and weights straight from colab, and when the time comes, we can simply import it from a .h5 file. it's BEAUTIFUL
